version: '3.7'
services:
  postgres:
    image: postgres:15.4
    env_file: .env
    container_name: $POSTGRES_HOST
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: $REDIS_HOST
    restart: unless-stopped
    env_file: .env
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  worker:
    build:
      context: .
    depends_on:
      - redis
      - app
    volumes_from:
      - app
    command: >
      sh -c "poetry run celery --workdir=./backend -A backend.celery.app worker --loglevel=INFO"

  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: app
    env_file: .env
    depends_on:
      - postgres
      - redis
    command: >
      sh -c "
        poetry run python3 backend/manage.py makemigrations &&
        poetry run python3 backend/manage.py migrate &&
        poetry run python3 backend/manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./backend:/app/backend

volumes:
  data:
  redis-data:
